/**
 * Kunta API
 * One API to rule them all. One API to find them, One API to bring them all and in the darkness bind them.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LocalizedValue', 'model/ServiceChannelAttachment', 'model/ServiceChannelServiceHour', 'model/ServiceChannelSupport', 'model/ServiceChannelWebPage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LocalizedValue'), require('./ServiceChannelAttachment'), require('./ServiceChannelServiceHour'), require('./ServiceChannelSupport'), require('./ServiceChannelWebPage'));
  } else {
    // Browser globals (root is window)
    if (!root.KuntaApiClient) {
      root.KuntaApiClient = {};
    }
    root.KuntaApiClient.ServiceElectronicChannel = factory(root.KuntaApiClient.ApiClient, root.KuntaApiClient.LocalizedValue, root.KuntaApiClient.ServiceChannelAttachment, root.KuntaApiClient.ServiceChannelServiceHour, root.KuntaApiClient.ServiceChannelSupport, root.KuntaApiClient.ServiceChannelWebPage);
  }
}(this, function(ApiClient, LocalizedValue, ServiceChannelAttachment, ServiceChannelServiceHour, ServiceChannelSupport, ServiceChannelWebPage) {
  'use strict';




  /**
   * The ServiceElectronicChannel model module.
   * @module model/ServiceElectronicChannel
   * @version 0.0.7
   */

  /**
   * Constructs a new <code>ServiceElectronicChannel</code>.
   * @alias module:model/ServiceElectronicChannel
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>ServiceElectronicChannel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServiceElectronicChannel} obj Optional instance to populate.
   * @return {module:model/ServiceElectronicChannel} The populated <code>ServiceElectronicChannel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('attachments')) {
        obj['attachments'] = ApiClient.convertToType(data['attachments'], [ServiceChannelAttachment]);
      }
      if (data.hasOwnProperty('urls')) {
        obj['urls'] = ApiClient.convertToType(data['urls'], [LocalizedValue]);
      }
      if (data.hasOwnProperty('requiresAuthentication')) {
        obj['requiresAuthentication'] = ApiClient.convertToType(data['requiresAuthentication'], 'Boolean');
      }
      if (data.hasOwnProperty('requiresSignature')) {
        obj['requiresSignature'] = ApiClient.convertToType(data['requiresSignature'], 'Boolean');
      }
      if (data.hasOwnProperty('signatureQuantity')) {
        obj['signatureQuantity'] = ApiClient.convertToType(data['signatureQuantity'], 'Integer');
      }
      if (data.hasOwnProperty('supportContacts')) {
        obj['supportContacts'] = ApiClient.convertToType(data['supportContacts'], [ServiceChannelSupport]);
      }
      if (data.hasOwnProperty('serviceHoursAdditinalInformation')) {
        obj['serviceHoursAdditinalInformation'] = ApiClient.convertToType(data['serviceHoursAdditinalInformation'], 'String');
      }
      if (data.hasOwnProperty('serviceHours')) {
        obj['serviceHours'] = ApiClient.convertToType(data['serviceHours'], [ServiceChannelServiceHour]);
      }
      if (data.hasOwnProperty('webPages')) {
        obj['webPages'] = ApiClient.convertToType(data['webPages'], [ServiceChannelWebPage]);
      }
      if (data.hasOwnProperty('shortDescriptions')) {
        obj['shortDescriptions'] = ApiClient.convertToType(data['shortDescriptions'], [LocalizedValue]);
      }
      if (data.hasOwnProperty('descriptions')) {
        obj['descriptions'] = ApiClient.convertToType(data['descriptions'], [LocalizedValue]);
      }
      if (data.hasOwnProperty('names')) {
        obj['names'] = ApiClient.convertToType(data['names'], [LocalizedValue]);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ServiceChannelAttachment>} attachments
   */
  exports.prototype['attachments'] = undefined;
  /**
   * @member {Array.<module:model/LocalizedValue>} urls
   */
  exports.prototype['urls'] = undefined;
  /**
   * @member {Boolean} requiresAuthentication
   */
  exports.prototype['requiresAuthentication'] = undefined;
  /**
   * @member {Boolean} requiresSignature
   */
  exports.prototype['requiresSignature'] = undefined;
  /**
   * @member {Integer} signatureQuantity
   */
  exports.prototype['signatureQuantity'] = undefined;
  /**
   * @member {Array.<module:model/ServiceChannelSupport>} supportContacts
   */
  exports.prototype['supportContacts'] = undefined;
  /**
   * @member {String} serviceHoursAdditinalInformation
   */
  exports.prototype['serviceHoursAdditinalInformation'] = undefined;
  /**
   * @member {Array.<module:model/ServiceChannelServiceHour>} serviceHours
   */
  exports.prototype['serviceHours'] = undefined;
  /**
   * @member {Array.<module:model/ServiceChannelWebPage>} webPages
   */
  exports.prototype['webPages'] = undefined;
  /**
   * @member {Array.<module:model/LocalizedValue>} shortDescriptions
   */
  exports.prototype['shortDescriptions'] = undefined;
  /**
   * @member {Array.<module:model/LocalizedValue>} descriptions
   */
  exports.prototype['descriptions'] = undefined;
  /**
   * @member {Array.<module:model/LocalizedValue>} names
   */
  exports.prototype['names'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;



  return exports;
}));


