/**
 * Kunta API
 * One API to rule them all. One API to find them, One API to bring them all and in the darkness bind them.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KuntaApiClient);
  }
}(this, function(expect, KuntaApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KuntaApiClient.Service();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Service', function() {
    it('should create an instance of Service', function() {
      // uncomment below and update the code to test Service
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be.a(KuntaApiClient.Service);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be();
    });

    it('should have the property shortDescriptions (base name: "shortDescriptions")', function() {
      // uncomment below and update the code to test the property shortDescriptions
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be();
    });

    it('should have the property descriptions (base name: "descriptions")', function() {
      // uncomment below and update the code to test the property descriptions
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be();
    });

    it('should have the property serviceUserInstructions (base name: "serviceUserInstructions")', function() {
      // uncomment below and update the code to test the property serviceUserInstructions
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be();
    });

    it('should have the property names (base name: "names")', function() {
      // uncomment below and update the code to test the property names
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be();
    });

    it('should have the property alternativeNames (base name: "alternativeNames")', function() {
      // uncomment below and update the code to test the property alternativeNames
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be();
    });

    it('should have the property classIds (base name: "classIds")', function() {
      // uncomment below and update the code to test the property classIds
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be();
    });

    it('should have the property electronicChannelIds (base name: "electronicChannelIds")', function() {
      // uncomment below and update the code to test the property electronicChannelIds
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be();
    });

    it('should have the property phoneChannelIds (base name: "phoneChannelIds")', function() {
      // uncomment below and update the code to test the property phoneChannelIds
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be();
    });

    it('should have the property printableFormChannelIds (base name: "printableFormChannelIds")', function() {
      // uncomment below and update the code to test the property printableFormChannelIds
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be();
    });

    it('should have the property serviceLocationChannelIds (base name: "serviceLocationChannelIds")', function() {
      // uncomment below and update the code to test the property serviceLocationChannelIds
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be();
    });

    it('should have the property webpageChannelIds (base name: "webpageChannelIds")', function() {
      // uncomment below and update the code to test the property webpageChannelIds
      //var instane = new KuntaApiClient.Service();
      //expect(instance).to.be();
    });

  });

}));
