/**
 * Kunta API
 * Solution to combine municipality services under single API.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package fi.metatavu.kuntaapi.client;

import fi.metatavu.kuntaapi.ApiException;
import fi.metatavu.kuntaapi.client.model.BadRequest;
import fi.metatavu.kuntaapi.client.model.Forbidden;
import fi.metatavu.kuntaapi.client.model.Incident;
import fi.metatavu.kuntaapi.client.model.InternalServerError;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IncidentsApi
 */
public class IncidentsApiTest {

    private final IncidentsApi api = new IncidentsApi();

    
    /**
     * Returns organizations incident by id
     *
     * Returns organizations incident by id 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findOrganizationIncidentTest() throws ApiException {
        String organizationId = null;
        String incidentId = null;
        // Incident response = api.findOrganizationIncident(organizationId, incidentId);

        // TODO: test validations
    }
    
    /**
     * Lists organizations incidents
     *
     * Lists organizations incidents 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listOrganizationIncidentsTest() throws ApiException {
        String organizationId = null;
        String slug = null;
        String startBefore = null;
        String endAfter = null;
        Integer area = null;
        Integer firstResult = null;
        Integer maxResults = null;
        String orderBy = null;
        String orderDir = null;
        // List<Incident> response = api.listOrganizationIncidents(organizationId, slug, startBefore, endAfter, area, firstResult, maxResults, orderBy, orderDir);

        // TODO: test validations
    }
    
}
