/**
 * Kunta API
 * Solution to combine municipality services under single API.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package fi.metatavu.kuntaapi.client;

import fi.metatavu.kuntaapi.ApiException;
import fi.metatavu.kuntaapi.client.model.BadRequest;
import fi.metatavu.kuntaapi.client.model.WebPageServiceChannel;
import fi.metatavu.kuntaapi.client.model.Forbidden;
import fi.metatavu.kuntaapi.client.model.InternalServerError;
import fi.metatavu.kuntaapi.client.model.NotFound;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebPageServiceChannelsApi
 */
public class WebPageServiceChannelsApiTest {

    private final WebPageServiceChannelsApi api = new WebPageServiceChannelsApi();

    
    /**
     * Finds a web page service channel by id
     *
     * Finds a web page service channel by id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findWebPageServiceChannelTest() throws ApiException {
        String webPageServiceChannelId = null;
        // WebPageServiceChannel response = api.findWebPageServiceChannel(webPageServiceChannelId);

        // TODO: test validations
    }
    
    /**
     * Lists web page service channels
     *
     * Lists web page service channels
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listWebPageServiceChannelsTest() throws ApiException {
        String organizationId = null;
        String search = null;
        String sortBy = null;
        String sortDir = null;
        Long firstResult = null;
        Long maxResults = null;
        // List<WebPageServiceChannel> response = api.listWebPageServiceChannels(organizationId, search, sortBy, sortDir, firstResult, maxResults);

        // TODO: test validations
    }
    
    /**
     * Updates a channel
     *
     * Updates a service channel
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateWebPageServiceChannelTest() throws ApiException {
        String webPageServiceChannelId = null;
        WebPageServiceChannel payload = null;
        // WebPageServiceChannel response = api.updateWebPageServiceChannel(webPageServiceChannelId, payload);

        // TODO: test validations
    }
    
}
